// flow-typed signature: 3293c963be65904c900cc0e9334c3cc8
// flow-typed version: <<STUB>>/node-vibrant_v^3.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-vibrant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-vibrant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-vibrant/data/node-example' {
  declare module.exports: any;
}

declare module 'node-vibrant/dist/474d262f2b165bfd49fe.worker' {
  declare module.exports: any;
}

declare module 'node-vibrant/dist/vibrant' {
  declare module.exports: any;
}

declare module 'node-vibrant/dist/vibrant.min' {
  declare module.exports: any;
}

declare module 'node-vibrant/dist/vibrant.worker' {
  declare module.exports: any;
}

declare module 'node-vibrant/dist/vibrant.worker.min' {
  declare module.exports: any;
}

declare module 'node-vibrant/karma.conf' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/browser' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/builder' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/bundle' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/bundle.worker' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/color' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/filter/default' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/filter/index' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/generator/default' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/generator/index' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/image/base' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/image/browser' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/image/node' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/index' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/index' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/mmcq' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/pqueue' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/vbox' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/worker' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/worker/common' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/worker/pool' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/quantizer/worker/worker' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/builder.spec' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/common/data' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/common/helper' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/common/server' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/vibrant.browser-spec' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/test/vibrant.spec' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/typing' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/util' {
  declare module.exports: any;
}

declare module 'node-vibrant/lib/vibrant' {
  declare module.exports: any;
}

declare module 'node-vibrant/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-vibrant/data/node-example.js' {
  declare module.exports: $Exports<'node-vibrant/data/node-example'>;
}
declare module 'node-vibrant/dist/474d262f2b165bfd49fe.worker.js' {
  declare module.exports: $Exports<'node-vibrant/dist/474d262f2b165bfd49fe.worker'>;
}
declare module 'node-vibrant/dist/vibrant.js' {
  declare module.exports: $Exports<'node-vibrant/dist/vibrant'>;
}
declare module 'node-vibrant/dist/vibrant.min.js' {
  declare module.exports: $Exports<'node-vibrant/dist/vibrant.min'>;
}
declare module 'node-vibrant/dist/vibrant.worker.js' {
  declare module.exports: $Exports<'node-vibrant/dist/vibrant.worker'>;
}
declare module 'node-vibrant/dist/vibrant.worker.min.js' {
  declare module.exports: $Exports<'node-vibrant/dist/vibrant.worker.min'>;
}
declare module 'node-vibrant/karma.conf.js' {
  declare module.exports: $Exports<'node-vibrant/karma.conf'>;
}
declare module 'node-vibrant/lib/browser.js' {
  declare module.exports: $Exports<'node-vibrant/lib/browser'>;
}
declare module 'node-vibrant/lib/builder.js' {
  declare module.exports: $Exports<'node-vibrant/lib/builder'>;
}
declare module 'node-vibrant/lib/bundle.js' {
  declare module.exports: $Exports<'node-vibrant/lib/bundle'>;
}
declare module 'node-vibrant/lib/bundle.worker.js' {
  declare module.exports: $Exports<'node-vibrant/lib/bundle.worker'>;
}
declare module 'node-vibrant/lib/color.js' {
  declare module.exports: $Exports<'node-vibrant/lib/color'>;
}
declare module 'node-vibrant/lib/filter/default.js' {
  declare module.exports: $Exports<'node-vibrant/lib/filter/default'>;
}
declare module 'node-vibrant/lib/filter/index.js' {
  declare module.exports: $Exports<'node-vibrant/lib/filter/index'>;
}
declare module 'node-vibrant/lib/generator/default.js' {
  declare module.exports: $Exports<'node-vibrant/lib/generator/default'>;
}
declare module 'node-vibrant/lib/generator/index.js' {
  declare module.exports: $Exports<'node-vibrant/lib/generator/index'>;
}
declare module 'node-vibrant/lib/image/base.js' {
  declare module.exports: $Exports<'node-vibrant/lib/image/base'>;
}
declare module 'node-vibrant/lib/image/browser.js' {
  declare module.exports: $Exports<'node-vibrant/lib/image/browser'>;
}
declare module 'node-vibrant/lib/image/node.js' {
  declare module.exports: $Exports<'node-vibrant/lib/image/node'>;
}
declare module 'node-vibrant/lib/index.js' {
  declare module.exports: $Exports<'node-vibrant/lib/index'>;
}
declare module 'node-vibrant/lib/quantizer/index.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/index'>;
}
declare module 'node-vibrant/lib/quantizer/mmcq.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/mmcq'>;
}
declare module 'node-vibrant/lib/quantizer/pqueue.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/pqueue'>;
}
declare module 'node-vibrant/lib/quantizer/vbox.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/vbox'>;
}
declare module 'node-vibrant/lib/quantizer/worker.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/worker'>;
}
declare module 'node-vibrant/lib/quantizer/worker/common.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/worker/common'>;
}
declare module 'node-vibrant/lib/quantizer/worker/pool.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/worker/pool'>;
}
declare module 'node-vibrant/lib/quantizer/worker/worker.js' {
  declare module.exports: $Exports<'node-vibrant/lib/quantizer/worker/worker'>;
}
declare module 'node-vibrant/lib/test/builder.spec.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/builder.spec'>;
}
declare module 'node-vibrant/lib/test/common/data.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/common/data'>;
}
declare module 'node-vibrant/lib/test/common/helper.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/common/helper'>;
}
declare module 'node-vibrant/lib/test/common/server.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/common/server'>;
}
declare module 'node-vibrant/lib/test/vibrant.browser-spec.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/vibrant.browser-spec'>;
}
declare module 'node-vibrant/lib/test/vibrant.spec.js' {
  declare module.exports: $Exports<'node-vibrant/lib/test/vibrant.spec'>;
}
declare module 'node-vibrant/lib/typing.js' {
  declare module.exports: $Exports<'node-vibrant/lib/typing'>;
}
declare module 'node-vibrant/lib/util.js' {
  declare module.exports: $Exports<'node-vibrant/lib/util'>;
}
declare module 'node-vibrant/lib/vibrant.js' {
  declare module.exports: $Exports<'node-vibrant/lib/vibrant'>;
}
declare module 'node-vibrant/webpack.config.js' {
  declare module.exports: $Exports<'node-vibrant/webpack.config'>;
}
